@hostname = http://localhost
@port = 8083
@suffix = /api/v1
@url = {{hostname}}:{{port}}{{suffix}}
@contentType = application/json

### Save Location
POST {{url}}/location/save
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "vehicle_id": "ZaKN9vRnBo",
  "lat": 1.0,
  "lng": 1.0
}

### Search Location
POST {{url}}/location/search
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "lat": 1.1,
  "lng": 1.0
}
