// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/orkungursel/hey-taxi-location-api/internal/domain/model"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetUsersByIds mocks base method.
func (m *MockUserService) GetUsersByIds(ctx context.Context, in []string) (map[string]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIds", ctx, in)
	ret0, _ := ret[0].(map[string]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIds indicates an expected call of GetUsersByIds.
func (mr *MockUserServiceMockRecorder) GetUsersByIds(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIds", reflect.TypeOf((*MockUserService)(nil).GetUsersByIds), ctx, in)
}
