// Code generated by MockGen. DO NOT EDIT.
// Source: proto/vehicle_service_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/orkungursel/hey-taxi-location-api/proto"
	grpc "google.golang.org/grpc"
)

// MockVehicleServiceClient is a mock of VehicleServiceClient interface.
type MockVehicleServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleServiceClientMockRecorder
}

// MockVehicleServiceClientMockRecorder is the mock recorder for MockVehicleServiceClient.
type MockVehicleServiceClientMockRecorder struct {
	mock *MockVehicleServiceClient
}

// NewMockVehicleServiceClient creates a new mock instance.
func NewMockVehicleServiceClient(ctrl *gomock.Controller) *MockVehicleServiceClient {
	mock := &MockVehicleServiceClient{ctrl: ctrl}
	mock.recorder = &MockVehicleServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleServiceClient) EXPECT() *MockVehicleServiceClientMockRecorder {
	return m.recorder
}

// GetVehicle mocks base method.
func (m *MockVehicleServiceClient) GetVehicle(ctx context.Context, in *proto.GetVehicleRequest, opts ...grpc.CallOption) (*proto.GetVehicleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVehicle", varargs...)
	ret0, _ := ret[0].(*proto.GetVehicleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicle indicates an expected call of GetVehicle.
func (mr *MockVehicleServiceClientMockRecorder) GetVehicle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicle", reflect.TypeOf((*MockVehicleServiceClient)(nil).GetVehicle), varargs...)
}

// MockVehicleServiceServer is a mock of VehicleServiceServer interface.
type MockVehicleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleServiceServerMockRecorder
}

// MockVehicleServiceServerMockRecorder is the mock recorder for MockVehicleServiceServer.
type MockVehicleServiceServerMockRecorder struct {
	mock *MockVehicleServiceServer
}

// NewMockVehicleServiceServer creates a new mock instance.
func NewMockVehicleServiceServer(ctrl *gomock.Controller) *MockVehicleServiceServer {
	mock := &MockVehicleServiceServer{ctrl: ctrl}
	mock.recorder = &MockVehicleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleServiceServer) EXPECT() *MockVehicleServiceServerMockRecorder {
	return m.recorder
}

// GetVehicle mocks base method.
func (m *MockVehicleServiceServer) GetVehicle(arg0 context.Context, arg1 *proto.GetVehicleRequest) (*proto.GetVehicleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicle", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetVehicleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicle indicates an expected call of GetVehicle.
func (mr *MockVehicleServiceServerMockRecorder) GetVehicle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicle", reflect.TypeOf((*MockVehicleServiceServer)(nil).GetVehicle), arg0, arg1)
}

// mustEmbedUnimplementedVehicleServiceServer mocks base method.
func (m *MockVehicleServiceServer) mustEmbedUnimplementedVehicleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedVehicleServiceServer")
}

// mustEmbedUnimplementedVehicleServiceServer indicates an expected call of mustEmbedUnimplementedVehicleServiceServer.
func (mr *MockVehicleServiceServerMockRecorder) mustEmbedUnimplementedVehicleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedVehicleServiceServer", reflect.TypeOf((*MockVehicleServiceServer)(nil).mustEmbedUnimplementedVehicleServiceServer))
}

// MockUnsafeVehicleServiceServer is a mock of UnsafeVehicleServiceServer interface.
type MockUnsafeVehicleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeVehicleServiceServerMockRecorder
}

// MockUnsafeVehicleServiceServerMockRecorder is the mock recorder for MockUnsafeVehicleServiceServer.
type MockUnsafeVehicleServiceServerMockRecorder struct {
	mock *MockUnsafeVehicleServiceServer
}

// NewMockUnsafeVehicleServiceServer creates a new mock instance.
func NewMockUnsafeVehicleServiceServer(ctrl *gomock.Controller) *MockUnsafeVehicleServiceServer {
	mock := &MockUnsafeVehicleServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeVehicleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeVehicleServiceServer) EXPECT() *MockUnsafeVehicleServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedVehicleServiceServer mocks base method.
func (m *MockUnsafeVehicleServiceServer) mustEmbedUnimplementedVehicleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedVehicleServiceServer")
}

// mustEmbedUnimplementedVehicleServiceServer indicates an expected call of mustEmbedUnimplementedVehicleServiceServer.
func (mr *MockUnsafeVehicleServiceServerMockRecorder) mustEmbedUnimplementedVehicleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedVehicleServiceServer", reflect.TypeOf((*MockUnsafeVehicleServiceServer)(nil).mustEmbedUnimplementedVehicleServiceServer))
}
